version: '3.7'

services:

  # alumni-app: 
  #   image: ${docker-registry}/alumni-app:1.0
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - alumni-project
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
      POSTGRES_DB: ${POSTGRESQL_DB}
    restart: always
    volumes:
        - postgres_db:/var/lib/postgresql/data

    ports:
      - "5433:5432"
    networks:
      - alumni-project
      
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    container_name: alumni-keycloak
    depends_on:
      - postgres
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD} 
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
    ports:
      - 8081:8080
    restart: unless-stopped
    networks:
      - alumni-project

volumes:
  postgres_db:
      driver: local
      
networks:
  alumni-project: